### ISSUE TITLE
Thanks, this is amazing.

### ISSUE THREAD

**Issue by ivan-avalos** [R3l3ntl3ss/Meme_Api#16]
I searched over the Internet for a random meme API, and this is the only one I found. Just a simple question: I plan to use your API for a public VS Code extension, and I wanted to know if your API is scalable enough to support many users. Each time my extension is installed, it will be fetching memes each five minutes, is that okay? Your project is amazing!

**Comment by ivan-avalos** [comment]
Here's the link to my project: https://github.com/ivan-avalos/vs-memes

**Comment by R3l3ntl3ss** [comment]
Thanks a lot, Ivan. I am glad you found it helpful. When I initially created it, I didn't think too much about scalability since I built it for personal use, but I was surprised to find out that it scaled pretty good. So feel free to use it and don't worry too much about overloading it. If you do come across any issue or error feel free to let me know and I will see how it could be resolved.
