### ISSUE TITLE
get memes from multiple subreddit 

### ISSUE THREAD

**Issue by narayanansampath** [R3l3ntl3ss/Meme_Api#26]
Can we get memes from multiple subreddits with count?

**Comment by R3l3ntl3ss** [comment]
Hey @narayanansampath , I realize I am a little late to your issue 😬, really sorry about that.

Querying from multiple subreddits can cause the API to become considerably slow since multiple requests to Reddit have to be made. Also, I am not sure if a lot of people would use this endpoint and I feel it is not worth the effort to create it. 

I am pretty sure you have moved on a different project and don't care about this issue anymore. I am sorry I couldn't get to it sooner.

**Comment by narayanansampath** [comment]
Hey @R3l3ntl3ss, 

First of all thank you for responding to my message. Secondly, what you have created is something beautiful and I'm sure many people will use your api to get quick data. When I was working on a small project I did use your api and the project is not in development anymore but I left it that way so your api is still in my code. The effort made to open source contribution is always worth the time so you should be proud of what you have created. 

Thanks,
Narayanan

**Comment by R3l3ntl3ss** [comment]
Thanks @narayanansampath , that means a lot. I am really glad you found my API helpful.
